# Generated by Django 3.1.4 on 2021-04-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('bd_date', models.DateTimeField(verbose_name='date of birth')),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(verbose_name='Initial date of employment')),
                ('date_end', models.DateTimeField(verbose_name='Final date of employment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.userinfo')),
            ],
        ),
    ]
