# Generated by Django 3.2 on 2021-04-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0002_alter_education_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='pages',
            new_name='grades',
        ),
    ]
